apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-auto
  name: test-auto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-auto
  strategy: {}
  template:
    metadata:
      labels:
        app: test-auto
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}